###
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json
Accept: application/json

{
  "user_name": "anhtr13",
  "user_email": "anhtr13@gmail.com",
  "password": "abc123"
}

###
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json
Accept: application/json

{
  "user_email": "anhtr13@gmail.com",
  "password": "abc123"
}

###
GET http://localhost:3000/api/v1/@/access_token?refresh_token=BTkX7M1h9fBbnC8wJKWRBm3DSx2Gyj9kqBX42i89Arz0WZ3cjopZIYqVoUf8K6XF
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/api/v1/@/info
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
POST http://localhost:3000/api/v1/auth/signout
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
GET http://localhost:3000/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
GET http://localhost:3000/api/v1/user/834a6fca-673f-4222-aff4-022ee7e997b7
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
POST http://localhost:3000/api/v1/user/834a6fca-673f-4222-aff4-022ee7e997b7/friend_request
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
POST http://localhost:3000/api/v1/group
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

{
  "group_name": "room 811"
}

###
GET http://localhost:3000/api/v1/group/366c0140-080c-4cb5-94e7-ca03b6aeb7bc/member
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
GET http://localhost:3000/api/v1/group/366c0140-080c-4cb5-94e7-ca03b6aeb7bc/invite
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
POST http://localhost:3000/api/v1/group/366c0140-080c-4cb5-94e7-ca03b6aeb7bc/invite/834a6fca-673f-4222-aff4-022ee7e997b7
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
GET http://localhost:3000/api/v1/@/group
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo

###
GET http://localhost:3000/api/v1/@/group_invite
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NGVkODhkLWQyYjEtNGZmZi1iNjA4LTk5MGQxMTdmZDViZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTIxNjE0OCwiaWF0IjoxNzU5MjE0MzQ4LCJqdGkiOiIwNTRlZDg4ZC1kMmIxLTRmZmYtYjYwOC05OTBkMTE3ZmQ1YmYifQ._HbyPiFU80ca6q7CML4rXxk0Zu0rzc7mxrx01Ss8Ibo
