###
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json
Accept: application/json

{
  "user_name": "anhtr13",
  "user_email": "anhtr13@gmail.com",
  "password": "abc123"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "user_email": "anhtr13@gmail.com",
  "password": "abc123"
}

###
POST http://localhost:3000/api/v1/auth/access_token?refresh_token=VhouL4JuXSXkmrwQV5gl0PNU1hSRZ-MEOd-R26kX2tjbiRr2IuhiLtiszhUwTq8Z
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/api/v1/me/info
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
POST http://localhost:3000/api/v1/auth/signout
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
GET http://localhost:3000/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
GET http://localhost:3000/api/v1/user/efc10ad7-c0cb-492f-aa11-a312b1fc4901
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
POST http://localhost:3000/api/v1/user/efc10ad7-c0cb-492f-aa11-a312b1fc4901/friend_request
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
POST http://localhost:3000/api/v1/room
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

{
  "room_name": "room 811"
}

###
GET http://localhost:3000/api/v1/room/77796d95-5bb0-4a12-af15-923446fee36f/member
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
GET http://localhost:3000/api/v1/room/77796d95-5bb0-4a12-af15-923446fee36f/invite
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
POST http://localhost:3000/api/v1/room/77796d95-5bb0-4a12-af15-923446fee36f/invite/834a6fca-673f-4222-aff4-022ee7e997b7
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
GET http://localhost:3000/api/v1/room
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk

###
GET http://localhost:3000/api/v1/room_invite
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNTA1Y2M0LWYwZTYtNDJjMC05NTdkLWI1MmVmNzcyZjk4ZiIsImVtYWlsIjoiYW5odHIxM0BnbWFpbC5jb20iLCJuYW1lIjoiYW5odHIxMyIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTQxOCwiaWF0IjoxNzU5OTE3NjE4LCJqdGkiOiI0ZDUwNWNjNC1mMGU2LTQyYzAtOTU3ZC1iNTJlZjc3MmY5OGYifQ.0vgJv_QQGqglfnz0yShYdcHvN593TGZdGl9lPjcAmGk
