###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "user_email": "anonymous.idiot@gmail.com",
  "password": "abc123"
}

###
GET http://localhost:3000/api/v1/me/info
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmYzEwYWQ3LWMwY2ItNDkyZi1hYTExLWEzMTJiMWZjNDkwMSIsImVtYWlsIjoiYW5vbnltb3VzLmlkaW90QGdtYWlsLmNvbSIsIm5hbWUiOiJpZGlvdCIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTM1NCwiaWF0IjoxNzU5OTE3NTU0LCJqdGkiOiJlZmMxMGFkNy1jMGNiLTQ5MmYtYWExMS1hMzEyYjFmYzQ5MDEifQ.vrPyajwwzvjJM9hlRVDTu0SSxy3Y2DeLpHxDaDEqK7U

###
GET http://localhost:3000/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmYzEwYWQ3LWMwY2ItNDkyZi1hYTExLWEzMTJiMWZjNDkwMSIsImVtYWlsIjoiYW5vbnltb3VzLmlkaW90QGdtYWlsLmNvbSIsIm5hbWUiOiJpZGlvdCIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTM1NCwiaWF0IjoxNzU5OTE3NTU0LCJqdGkiOiJlZmMxMGFkNy1jMGNiLTQ5MmYtYWExMS1hMzEyYjFmYzQ5MDEifQ.vrPyajwwzvjJM9hlRVDTu0SSxy3Y2DeLpHxDaDEqK7U

###
GET http://localhost:3000/api/v1/friend_request
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmYzEwYWQ3LWMwY2ItNDkyZi1hYTExLWEzMTJiMWZjNDkwMSIsImVtYWlsIjoiYW5vbnltb3VzLmlkaW90QGdtYWlsLmNvbSIsIm5hbWUiOiJpZGlvdCIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTM1NCwiaWF0IjoxNzU5OTE3NTU0LCJqdGkiOiJlZmMxMGFkNy1jMGNiLTQ5MmYtYWExMS1hMzEyYjFmYzQ5MDEifQ.vrPyajwwzvjJM9hlRVDTu0SSxy3Y2DeLpHxDaDEqK7U

###
POST http://localhost:3000/api/v1/friend_request/16762505-7302-4216-9aac-7ed84bb177d8
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmYzEwYWQ3LWMwY2ItNDkyZi1hYTExLWEzMTJiMWZjNDkwMSIsImVtYWlsIjoiYW5vbnltb3VzLmlkaW90QGdtYWlsLmNvbSIsIm5hbWUiOiJpZGlvdCIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTM1NCwiaWF0IjoxNzU5OTE3NTU0LCJqdGkiOiJlZmMxMGFkNy1jMGNiLTQ5MmYtYWExMS1hMzEyYjFmYzQ5MDEifQ.vrPyajwwzvjJM9hlRVDTu0SSxy3Y2DeLpHxDaDEqK7U

###
GET http://localhost:3000/api/v1/friend
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmYzEwYWQ3LWMwY2ItNDkyZi1hYTExLWEzMTJiMWZjNDkwMSIsImVtYWlsIjoiYW5vbnltb3VzLmlkaW90QGdtYWlsLmNvbSIsIm5hbWUiOiJpZGlvdCIsInN1YiI6ImFjY2Vzc190b2tlbiIsImV4cCI6MTc1OTkxOTM1NCwiaWF0IjoxNzU5OTE3NTU0LCJqdGkiOiJlZmMxMGFkNy1jMGNiLTQ5MmYtYWExMS1hMzEyYjFmYzQ5MDEifQ.vrPyajwwzvjJM9hlRVDTu0SSxy3Y2DeLpHxDaDEqK7U
