// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
	users (
		"user_email",
		"user_name",
		"password",
		"profile_image",
		"created_at"
	)
VALUES
	($1, $2, $3, $4, $5)
RETURNING
	"user_id",
	"user_email",
	"user_name",
	"profile_image",
	"created_at"
`

type CreateUserParams struct {
	UserEmail    string           `json:"user_email"`
	UserName     string           `json:"user_name"`
	Password     string           `json:"password"`
	ProfileImage pgtype.Text      `json:"profile_image"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type CreateUserRow struct {
	UserID       pgtype.UUID      `json:"user_id"`
	UserEmail    string           `json:"user_email"`
	UserName     string           `json:"user_name"`
	ProfileImage pgtype.Text      `json:"profile_image"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserEmail,
		arg.UserName,
		arg.Password,
		arg.ProfileImage,
		arg.CreatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.ProfileImage,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
	user_id, user_email, user_name, password, profile_image, created_at
FROM
	users
WHERE
	user_email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, userEmail string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Password,
		&i.ProfileImage,
		&i.CreatedAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT
	user_id, user_email, user_name, password, profile_image, created_at
FROM
	users
WHERE
	user_id = $1
`

func (q *Queries) FindUserById(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.Password,
		&i.ProfileImage,
		&i.CreatedAt,
	)
	return i, err
}

const findUserInfoById = `-- name: FindUserInfoById :one
SELECT
	user_id,
	user_name,
	profile_image
FROM
	users
WHERE
	user_id = $1
`

type FindUserInfoByIdRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserName     string      `json:"user_name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}

func (q *Queries) FindUserInfoById(ctx context.Context, userID pgtype.UUID) (FindUserInfoByIdRow, error) {
	row := q.db.QueryRow(ctx, findUserInfoById, userID)
	var i FindUserInfoByIdRow
	err := row.Scan(&i.UserID, &i.UserName, &i.ProfileImage)
	return i, err
}

const getAllUserInfo = `-- name: GetAllUserInfo :many
SELECT
	user_id,
	user_name,
	profile_image
FROM
	users
ORDER BY
	user_id ASC
LIMIT
	$1
OFFSET
	$2
`

type GetAllUserInfoParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllUserInfoRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserName     string      `json:"user_name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}

func (q *Queries) GetAllUserInfo(ctx context.Context, arg GetAllUserInfoParams) ([]GetAllUserInfoRow, error) {
	rows, err := q.db.Query(ctx, getAllUserInfo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserInfoRow{}
	for rows.Next() {
		var i GetAllUserInfoRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.ProfileImage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInfoByName = `-- name: GetUserInfoByName :many
SELECT
	user_id,
	user_name,
	profile_image
FROM
	users
WHERE
	user_name LIKE ('%' || $1 || '%')
ORDER BY
	user_id
LIMIT
	$2
OFFSET
	$3
`

type GetUserInfoByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetUserInfoByNameRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserName     string      `json:"user_name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}

func (q *Queries) GetUserInfoByName(ctx context.Context, arg GetUserInfoByNameParams) ([]GetUserInfoByNameRow, error) {
	rows, err := q.db.Query(ctx, getUserInfoByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserInfoByNameRow{}
	for rows.Next() {
		var i GetUserInfoByNameRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.ProfileImage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET
	user_name = $1,
	password = $2,
	profile_image = $3
WHERE
	user_id = $4
RETURNING
	"user_id",
	"user_email",
	"user_name",
	"profile_image"
`

type UpdateUserInfoParams struct {
	UserName     string      `json:"user_name"`
	Password     string      `json:"password"`
	ProfileImage pgtype.Text `json:"profile_image"`
	UserID       pgtype.UUID `json:"user_id"`
}

type UpdateUserInfoRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	UserEmail    string      `json:"user_email"`
	UserName     string      `json:"user_name"`
	ProfileImage pgtype.Text `json:"profile_image"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UpdateUserInfoRow, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.UserName,
		arg.Password,
		arg.ProfileImage,
		arg.UserID,
	)
	var i UpdateUserInfoRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.ProfileImage,
	)
	return i, err
}
