# BUILDER --------------------------------
FROM golang:latest AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/socket 


# RUNNER --------------------------------
FROM alpine:latest AS runner
WORKDIR /app

COPY --from=builder /app/main ./

ENTRYPOINT ["./main"]
